namespace: WackoPicko
output:
  file_path: ./Fluid-Attacks-Results.csv
  format: CSV
strict: true
working_dir: .
language: EN
sast:
  include:
    - .
  exclude:
    - glob(**/node_modules/**)
    - glob(**/test/**)